const { 
    SlashCommandBuilder, 
    MessageFlags, 
    AttachmentBuilder, 
    ButtonBuilder, 
    ButtonStyle, 
    ContainerBuilder,
    SectionBuilder,
    TextDisplayBuilder,
    ActionRowBuilder, 
    SeparatorBuilder, 
    ThumbnailBuilder,           
    MediaGalleryBuilder,        
    MediaGalleryItemBuilder,    
    SeparatorSpacingSize,
    PermissionFlagsBits 
} = require('discord.js');

const { createWelcomeImage } = require('../../../welcomeCanvas12.js'); // Adjust path if needed
const { fetchAdvancedProfile } = require('../../../utils/v9Scraper'); // Adjust path if needed

module.exports = {
    data: new SlashCommandBuilder()
        .setName('test-welcome')
        .setDescription('Simulate the welcome message and image generator.')
        .setDefaultMemberPermissions(PermissionFlagsBits.Administrator) // ✅ Locked to Admins
        .addUserOption(opt => opt.setName('target')
            .setDescription('Test the welcome image on a specific user (defaults to you)')
            .setRequired(false)
        ),

    async execute(interaction) {
        // 1. Defer the reply because scraping and canvas generation take a few seconds
        await interaction.deferReply();

        // 2. Get the target member
        const targetUserOption = interaction.options.getUser('target') || interaction.user;
        const member = await interaction.guild.members.fetch(targetUserOption.id).catch(() => null);

        if (!member) {
            return interaction.editReply({ content: "❌ **Error:** Could not find that member in this server." });
        }

        try {
            // 3. FETCH NITRO PROFILE THEME COLORS
            const v9Data = await fetchAdvancedProfile(member.id);
            let themeColors = null;
            let containerColor = 8947848; // ✅ Default #888888 in decimal

            if (v9Data && v9Data.user_profile?.theme_colors) {
                themeColors = v9Data.user_profile.theme_colors; 
                containerColor = themeColors[0]; // ✅ Primary color from the Nitro theme
            }

            // 4. GENERATE THE IMAGE & GET AVATAR STATE
            // Destructure the returned object from the updated canvas function!
            const { welcomeImage, avatarAsset, isFallback } = await createWelcomeImage(member, themeColors);
            
            const files = [new AttachmentBuilder(welcomeImage, { name: 'welcome-image.png' })];
            let thumbnailURL = member.user.displayAvatarURL({ extension: 'png', size: 512 });

            // ✅ IF AVATAR FAILED TO LOAD: Use the square #888888 thumbnail generated by the canvas
            if (isFallback && avatarAsset) {
                const avatarAttachment = new AttachmentBuilder(avatarAsset, { name: 'avatar-target.png' });
                files.push(avatarAttachment);
                thumbnailURL = 'attachment://avatar-target.png';
            }
            
            // 5. MOCK DATA FOR THE TEST UI
            const accountCreated = `<t:${Math.floor(member.user.createdTimestamp / 1000)}:R>`;
            const inviterId = interaction.user.id; // Mock inviter
            const inviteCode = "testCode"; // Mock code
            
            // 6. BUILD EXACT SAME CONTAINER
            const mainContainer = new ContainerBuilder()
                .setAccentColor(containerColor) 
                .addSectionComponents(
                    new SectionBuilder()
                        .setThumbnailAccessory(
                            new ThumbnailBuilder()
                                .setURL(thumbnailURL) // ✅ Dynamically switches to the #888888 square attachment if needed
                        )
                        .addTextDisplayComponents(
                            new TextDisplayBuilder().setContent(`### Welcome to ${member.guild.name} Server (TEST)`),
                            new TextDisplayBuilder().setContent(
                                `-# <@${member.user.id}> \`(${member.user.username})\`\n` +
                                `-# <:calendar:1470475413175144530> Account Created: ${accountCreated}\n` +
                                `-# <:members:1468470163081924608> Member Count: \`${member.guild.memberCount}\`\n` +
                                `-# <:connection:1468633345876431021> Invited by <@${inviterId}> \`(Test_Inviter)\` using [\`${inviteCode}\`](https://discord.gg/${inviteCode}) invite`
                            )
                        )
                )
                .addActionRowComponents(
                    new ActionRowBuilder()
                        .addComponents(
                            new ButtonBuilder()
                                .setStyle(ButtonStyle.Link)
                                .setLabel("Register Here")
                                .setEmoji('📝')
                                .setURL("https://discord.com/channels/1456197054782111756/1456197056250122352")
                        )
                )
                .addSeparatorComponents(
                    new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
                )
                .addMediaGalleryComponents(
                    new MediaGalleryBuilder()
                        .addItems(
                            new MediaGalleryItemBuilder()
                                .setURL("attachment://welcome-image.png")
                                .setDescription(`${member.user.globalName || member.user.username} just joined!`)
                        )
                );

            // 7. SEND THE REPLY
            await interaction.editReply({ 
                flags: [MessageFlags.IsComponentsV2],
                files: files,
                components: [mainContainer]
            });

        } catch (error) {
            console.error("Test Command Error:", error);
            await interaction.editReply({ content: "❌ **Error:** Something went wrong generating the test welcome." });
        }
    }
};
